const COURSE_INTROS = {
  spanish: {
    id: 0,
    title: "Introduction to Spanish",
    intro:
      "Spanish is spoken by over 500 million people worldwide. This introductory lesson covers pronunciation basics, common sounds, and the learning path ahead—before you dive into vocabulary and quizzes.",
    objectives: [
      "Understand how lessons and quizzes work on LinguaLift",
      "Learn basic Spanish pronunciation tips",
      "Recognize essential courtesy words",
      "Prepare for your first graded quiz",
    ],
    grammar:
      "Spanish is phonetic: letters are pronounced consistently. Roll your R's lightly, and stress the correct syllable (often shown with an accent mark, e.g. café).",
    vocab: [
      { term: "Sí / No", meaning: "Yes / No" },
      { term: "Por favor", meaning: "Please" },
      { term: "Gracias", meaning: "Thank you" },
      { term: "Hola", meaning: "Hello" },
    ],
    phrases: [
      { term: "¿Cómo se dice…?", meaning: "How do you say…?" },
      { term: "No entiendo", meaning: "I don't understand" },
      { term: "Más despacio, por favor", meaning: "Slower, please" },
    ],
    quiz: [
      { type: "mcq", q: "How many people speak Spanish worldwide (approximately)?", options: ["50 million", "500 million", "5 million", "50 thousand"], a: "500 million" },
      { type: "mcq", q: "Spanish spelling is generally:", options: ["Random", "Phonetic (read as written)", "Identical to English", "Only symbols"], a: "Phonetic (read as written)" },
      { type: "mcq", q: "What does 'Gracias' mean?", options: ["Please", "Thank you", "Hello", "Goodbye"], a: "Thank you" },
      { type: "mcq", q: "You're in a Spanish class and don't follow what the teacher said. You say:", options: ["Más despacio, por favor", "Gracias", "Hola", "Sí"], a: "Más despacio, por favor" },
      { type: "fill", q: "Complete: ___ favor (please)", a: "por" },
      { type: "mcq", q: "Which phrase would you use to ask how to say something in Spanish?", options: ["No entiendo", "¿Cómo se dice…?", "Gracias", "Más despacio"], a: "¿Cómo se dice…?" },
      { type: "fill", q: "I don't understand: No ___", a: "entiendo" },
      { type: "mcq", q: "The accent mark in 'café' tells you to:", options: ["Whisper the word", "Stress the last syllable", "Skip the letter", "Pronounce it silently"], a: "Stress the last syllable" },
    ],
  },
  french: {
    id: 0,
    title: "Introduction to French",
    intro:
      "French is an official language in dozens of countries. Start here to learn how the course works, pick up first words, and build confidence before unit quizzes.",
    objectives: [
      "Learn how to navigate lessons step by step",
      "Master basic French sounds and greetings",
      "Use essential classroom phrases",
      "Pass your first introductory quiz",
    ],
    grammar:
      "French has nasal vowels (on, in, un) and silent final consonants. Liaison links words across boundaries in fluent speech.",
    vocab: [
      { term: "Oui / Non", meaning: "Yes / No" },
      { term: "Bonjour", meaning: "Hello" },
      { term: "Merci", meaning: "Thank you" },
      { term: "Pardon", meaning: "Sorry / Excuse me" },
    ],
    phrases: [
      { term: "Je ne comprends pas", meaning: "I don't understand" },
      { term: "Répétez, s'il vous plaît", meaning: "Repeat, please" },
    ],
    quiz: [
      { type: "mcq", q: "You walk into a bakery in Paris. The first thing you should say is:", options: ["Merci", "Bonjour", "Pardon", "Non"], a: "Bonjour" },
      { type: "mcq", q: "What does 'Merci' mean?", options: ["Please", "Thank you", "Goodbye", "Hello"], a: "Thank you" },
      { type: "fill", q: "Yes: ___", a: "oui" },
      { type: "mcq", q: "Your French teacher speaks too quickly. You say:", options: ["Bonjour", "Merci", "Répétez, s'il vous plaît", "Oui"], a: "Répétez, s'il vous plaît" },
      { type: "mcq", q: "In French, the final consonant of a word is usually:", options: ["Doubled", "Silent", "Shouted", "Replaced with a vowel"], a: "Silent" },
      { type: "fill", q: "I don't understand: Je ne ___ pas", a: "comprends" },
      { type: "mcq", q: "What is 'liaison' in French?", options: ["A type of bread", "Linking sounds between words", "A formal greeting", "A writing rule"], a: "Linking sounds between words" },
      { type: "fill", q: "Sorry / Excuse me: ___", a: "pardon" },
    ],
  },
  german: {
    id: 0,
    title: "Introduction to German",
    intro:
      "German is the most widely spoken native language in Europe. This unit introduces pronunciation, study tips, and your first survival phrases before graded lessons.",
    objectives: [
      "Understand the lesson → quiz flow",
      "Learn German capitalization rules for nouns",
      "Recognize basic greetings and classroom phrases",
      "Complete the introductory quiz",
    ],
    grammar:
      "All German nouns are capitalized (der Mann = the man). Word order in statements often places the verb second.",
    vocab: [
      { term: "Ja / Nein", meaning: "Yes / No" },
      { term: "Hallo", meaning: "Hello" },
      { term: "Danke", meaning: "Thank you" },
      { term: "Bitte", meaning: "Please" },
    ],
    phrases: [
      { term: "Ich verstehe nicht", meaning: "I don't understand" },
      { term: "Können Sie das wiederholen?", meaning: "Can you repeat that?" },
    ],
    quiz: [
      { type: "mcq", q: "Which is written correctly in German?", options: ["der mann", "Der Mann", "DER MANN", "der Mann"], a: "Der Mann" },
      { type: "mcq", q: "Someone helps you carry your bags. You say:", options: ["Bitte", "Nein", "Danke", "Hallo"], a: "Danke" },
      { type: "fill", q: "Hello: ___", a: "hallo" },
      { type: "mcq", q: "You're lost in Berlin and don't understand directions. You say:", options: ["Danke", "Ich verstehe nicht", "Ja", "Hallo"], a: "Ich verstehe nicht" },
      { type: "mcq", q: "In a basic German sentence like 'Ich bin müde' (I am tired), the verb is in position:", options: ["First", "Second", "Last", "Third"], a: "Second" },
      { type: "fill", q: "Yes: ___", a: "ja" },
      { type: "mcq", q: "You want someone to repeat what they said. You ask:", options: ["Ich verstehe nicht", "Können Sie das wiederholen?", "Danke", "Ja"], a: "Können Sie das wiederholen?" },
      { type: "fill", q: "Please: ___", a: "bitte" },
    ],
  },
  japanese: {
    id: 0,
    title: "Introduction to Japanese",
    intro:
      "Japanese uses three writing systems (hiragana, katakana, kanji). Begin with greetings, politeness levels, and how to study effectively before taking quizzes.",
    objectives: [
      "Learn the lesson structure before quizzes",
      "Understand polite vs. casual speech",
      "Master first greetings and classroom phrases",
      "Pass the intro quiz",
    ],
    grammar:
      "Politeness matters: です/ます forms are safe defaults. Bow slightly when greeting. Particles (は, を, が) mark grammatical roles.",
    vocab: [
      { term: "はい / いいえ", meaning: "Yes / No" },
      { term: "こんにちは", meaning: "Hello" },
      { term: "ありがとう", meaning: "Thank you" },
      { term: "すみません", meaning: "Excuse me / Sorry" },
    ],
    phrases: [
      { term: "わかりません", meaning: "I don't understand" },
      { term: "もう一度お願いします", meaning: "Once more, please" },
    ],
    quiz: [
      { type: "mcq", q: "Which three writing systems does Japanese use?", options: ["Hiragana, Katakana, Kanji", "Cyrillic, Latin, Greek", "Hangul, Hanja, Latin", "Arabic, Hebrew, Latin"], a: "Hiragana, Katakana, Kanji" },
      { type: "mcq", q: "You accidentally bump into someone on the train. You say:", options: ["ありがとう", "すみません", "こんにちは", "いいえ"], a: "すみません" },
      { type: "mcq", q: "Which ending indicates polite speech?", options: ["です/ます", "だ/する", "ね/よ", "の/か"], a: "です/ます" },
      { type: "mcq", q: "Your teacher explains something and you're completely lost. You say:", options: ["はい", "わかりません", "ありがとう", "こんにちは"], a: "わかりません" },
      { type: "mcq", q: "When meeting someone for the first time in Japan, it is polite to:", options: ["Hug them", "Bow slightly", "Give a thumbs up", "Wink"], a: "Bow slightly" },
      { type: "mcq", q: "The particle は (wa) is used to:", options: ["End a sentence", "Mark the topic of a sentence", "Express emotion", "Ask a question"], a: "Mark the topic of a sentence" },
      { type: "mcq", q: "You want someone to say something again. You say:", options: ["すみません", "もう一度お願いします", "ありがとう", "いいえ"], a: "もう一度お願いします" },
      { type: "mcq", q: "A friend gives you a gift. You say:", options: ["すみません", "いいえ", "ありがとう", "わかりません"], a: "ありがとう" },
    ],
  },
  italian: {
    id: 0,
    title: "Introduction to Italian",
    intro:
      "Italian is known for clear vowels and expressive intonation. This first unit explains the course format and teaches essential words before you progress.",
    objectives: [
      "Navigate multi-step lessons before each quiz",
      "Pronounce Italian vowels clearly",
      "Use basic greetings and classroom phrases",
      "Score 70%+ on the intro quiz",
    ],
    grammar:
      "Italian vowels (a, e, i, o, u) are pronounced fully. Double consonants are held longer (nonno vs. nono).",
    vocab: [
      { term: "Sì / No", meaning: "Yes / No" },
      { term: "Ciao", meaning: "Hi / Bye (informal)" },
      { term: "Grazie", meaning: "Thank you" },
      { term: "Prego", meaning: "Please / You're welcome" },
    ],
    phrases: [
      { term: "Non capisco", meaning: "I don't understand" },
      { term: "Può ripetere?", meaning: "Can you repeat?" },
    ],
    quiz: [
      { type: "mcq", q: "How are Italian vowels (a, e, i, o, u) typically pronounced?", options: ["Silently", "Clearly and fully", "Only at the start of words", "The same as in English"], a: "Clearly and fully" },
      { type: "mcq", q: "You run into a friend on the street in Rome. You say:", options: ["Prego", "Grazie", "Ciao", "Non capisco"], a: "Ciao" },
      { type: "fill", q: "I don't understand: Non ___", a: "capisco" },
      { type: "mcq", q: "What is the difference between 'nonno' and 'nono'?", options: ["They mean the same thing", "The double 'n' is held longer, changing the meaning", "One is formal, one is informal", "One is a verb, one is a noun"], a: "The double 'n' is held longer, changing the meaning" },
      { type: "mcq", q: "Someone holds the door for you. You say:", options: ["Ciao", "No", "Grazie", "Non capisco"], a: "Grazie" },
      { type: "fill", q: "Thank you: ___", a: "grazie" },
      { type: "mcq", q: "Your Italian tutor speaks too quickly and you're confused. You ask:", options: ["Ciao!", "Può ripetere?", "Prego", "Sì"], a: "Può ripetere?" },
      { type: "fill", q: "Can you repeat?: Può ___?", a: "ripetere" },
    ],
  },
};

const COURSES = {
  spanish: {
    name: "Spanish",
    flag: "🇪🇸",
    native: "Español",
    lessons: [
      {
        id: 1,
        title: "Greetings & Introductions",
        intro:
          "Before the quiz, you'll learn how to greet people, introduce yourself, and use polite words in everyday Spanish conversations.",
        objectives: [
          "Greet people at different times of day",
          "Say please, thank you, and goodbye",
          "Introduce yourself and ask someone's name",
        ],
        grammar: "Spanish greetings vary by time of day. Use tú (informal) with friends and usted (formal) with strangers or elders.",
        vocab: [
          { term: "Hola", meaning: "Hello" },
          { term: "Buenos días", meaning: "Good morning" },
          { term: "Buenas tardes", meaning: "Good afternoon" },
          { term: "Buenas noches", meaning: "Good evening / night" },
          { term: "Adiós", meaning: "Goodbye" },
          { term: "Por favor", meaning: "Please" },
          { term: "Gracias", meaning: "Thank you" },
        ],
        phrases: [
          { term: "¿Cómo te llamas?", meaning: "What is your name? (informal)" },
          { term: "Me llamo…", meaning: "My name is…" },
          { term: "Mucho gusto", meaning: "Nice to meet you" },
        ],
        quiz: [
          { type: "mcq", q: "It's 3 PM and you greet a colleague. Which greeting fits best?", options: ["Buenos días", "Buenas tardes", "Buenas noches", "Adiós"], a: "Buenas tardes" },
          { type: "mcq", q: "You meet someone at a party. After exchanging names, you say:", options: ["Adiós", "Mucho gusto", "Por favor", "Buenos días"], a: "Mucho gusto" },
          { type: "fill", q: "What's your name? (informal): ¿Cómo te ___?", a: "llamas" },
          { type: "mcq", q: "Which word would you use with an elderly stranger instead of 'tú'?", options: ["Yo", "Usted", "Nosotros", "Ellos"], a: "Usted" },
          { type: "fill", q: "My name is…: Me ___…", a: "llamo" },
          { type: "mcq", q: "You're leaving a shop after buying something. The shopkeeper says 'Gracias.' You reply:", options: ["Adiós", "Hola", "Buenos días", "Gracias a usted"], a: "Gracias a usted" },
          { type: "mcq", q: "It's 10 PM. Which greeting would you use?", options: ["Buenos días", "Buenas tardes", "Buenas noches", "Hola, buenos días"], a: "Buenas noches" },
          { type: "fill", q: "Goodbye: ___", a: "adiós" },
          { type: "mcq", q: "Someone asks '¿Cómo te llamas?' What are they asking?", options: ["How are you?", "Where are you from?", "What is your name?", "How old are you?"], a: "What is your name?" },
          { type: "mcq", q: "Which pair correctly shows formal vs. informal 'you'?", options: ["tú / usted", "yo / él", "nosotros / ellos", "ella / usted"], a: "tú / usted" },
        ],
      },
      {
        id: 2,
        title: "Numbers & Basics",
        intro: "Numbers help you shop, tell time, and understand prices. Study these digits before answering quiz questions.",
        objectives: [
          "Count from one to fifteen in Spanish",
          "Ask how much something costs",
          "Use numbers in simple phrases",
        ],
        grammar: "Numbers 1–15 are essential for shopping and schedules. Uno changes to un before masculine nouns (un libro).",
        vocab: [
          { term: "uno", meaning: "one" },
          { term: "dos", meaning: "two" },
          { term: "tres", meaning: "three" },
          { term: "cuatro", meaning: "four" },
          { term: "cinco", meaning: "five" },
          { term: "diez", meaning: "ten" },
          { term: "quince", meaning: "fifteen" },
        ],
        phrases: [
          { term: "¿Cuánto cuesta?", meaning: "How much does it cost?" },
          { term: "Son cinco euros", meaning: "It's five euros" },
        ],
        quiz: [
          { type: "mcq", q: "You're at a market and want to know the price of an item. You ask:", options: ["¿Cómo te llamas?", "¿Cuánto cuesta?", "¿Buenos días?", "¿Dónde está?"], a: "¿Cuánto cuesta?" },
          { type: "fill", q: "The number 5 in Spanish: ___", a: "cinco" },
          { type: "mcq", q: "A vendor says 'Son tres euros.' How much do you owe?", options: ["1 euro", "3 euros", "5 euros", "15 euros"], a: "3 euros" },
          { type: "mcq", q: "Before a masculine noun, 'uno' changes to:", options: ["una", "un", "unos", "unas"], a: "un" },
          { type: "fill", q: "Ten: ___", a: "diez" },
          { type: "mcq", q: "Put these numbers in order: tres, uno, cinco, dos", options: ["uno, dos, tres, cinco", "tres, uno, cinco, dos", "cinco, tres, dos, uno", "dos, uno, tres, cinco"], a: "uno, dos, tres, cinco" },
          { type: "fill", q: "Fifteen: ___", a: "quince" },
          { type: "mcq", q: "You buy 4 apples. How do you say '4' in Spanish?", options: ["tres", "cinco", "cuatro", "dos"], a: "cuatro" },
          { type: "mcq", q: "Which sentence correctly says 'It's five euros'?", options: ["Son cinco euros", "Cuánto cinco euros", "Cinco son euros", "Es cuesta cinco"], a: "Son cinco euros" },
          { type: "fill", q: "Two: ___", a: "dos" },
        ],
      },
      {
        id: 3,
        title: "Everyday Verbs",
        intro: "Verbs let you describe actions. This lesson covers common verbs and simple sentences before your quiz.",
        objectives: [
          "Recognize five essential verbs",
          "Understand basic -ar verb patterns",
          "Read simple subject + verb sentences",
        ],
        grammar: "Regular -ar verbs: remove -ar and add -o, -as, -a… Example: hablar → hablo (I speak).",
        vocab: [
          { term: "hablar", meaning: "to speak" },
          { term: "estudiar", meaning: "to study" },
          { term: "trabajar", meaning: "to work" },
          { term: "comer", meaning: "to eat" },
          { term: "vivir", meaning: "to live" },
        ],
        phrases: [
          { term: "Yo hablo español", meaning: "I speak Spanish" },
          { term: "Ella estudia mucho", meaning: "She studies a lot" },
        ],
        quiz: [
          { type: "mcq", q: "To conjugate 'hablar' for 'I', you remove '-ar' and add:", options: ["-o", "-as", "-a", "-an"], a: "-o" },
          { type: "fill", q: "I speak: Yo ___ (hablar)", a: "hablo" },
          { type: "mcq", q: "Your friend asks what you do for a living. You say 'Yo trabajo.' What verb is this from?", options: ["hablar", "trabajar", "estudiar", "vivir"], a: "trabajar" },
          { type: "mcq", q: "'Ella estudia mucho' means:", options: ["She works a lot", "She studies a lot", "She eats a lot", "She lives far away"], a: "She studies a lot" },
          { type: "fill", q: "To eat: ___", a: "comer" },
          { type: "mcq", q: "Which verb does NOT end in '-ar'?", options: ["hablar", "estudiar", "comer", "trabajar"], a: "comer" },
          { type: "mcq", q: "If 'hablar' → 'hablo' (I speak), then 'estudiar' → ___ (I study):", options: ["estudio", "estudias", "estudia", "estudiamos"], a: "estudio" },
          { type: "fill", q: "To live: ___", a: "vivir" },
          { type: "mcq", q: "Which sentence means 'I speak Spanish'?", options: ["Yo como español", "Yo hablo español", "Yo vivo español", "Yo estudio español"], a: "Yo hablo español" },
          { type: "mcq", q: "The verbs 'comer' and 'vivir' belong to which verb groups?", options: ["-ar and -ar", "-er and -ir", "-ar and -ir", "-er and -er"], a: "-er and -ir" },
        ],
      },
      {
        id: 4,
        title: "Family & People",
        grammar: "Possessive adjectives agree in number: mi hermano (my brother), mis hermanos (my siblings). Nuestro/nuestra also agree in gender.",
        vocab: [
          { term: "madre", meaning: "mother" },
          { term: "padre", meaning: "father" },
          { term: "hermano / hermana", meaning: "brother / sister" },
          { term: "hijo / hija", meaning: "son / daughter" },
          { term: "abuelo / abuela", meaning: "grandfather / grandmother" },
          { term: "amigo / amiga", meaning: "friend (m. / f.)" },
          { term: "esposo / esposa", meaning: "husband / wife" },
        ],
        phrases: [
          { term: "¿Tienes hermanos?", meaning: "Do you have siblings?" },
          { term: "Mi familia es grande", meaning: "My family is big" },
          { term: "Este es mi padre", meaning: "This is my father" },
        ],
        quiz: [
          { type: "mcq", q: "How do you say 'mother' in Spanish?", options: ["padre", "madre", "hermana", "hija"], a: "madre" },
          { type: "fill", q: "My brother: ___ hermano", a: "mi" },
          { type: "mcq", q: "Your friend introduces a man as 'mi abuelo.' Who is he?", options: ["Her father", "Her brother", "Her grandfather", "Her son"], a: "Her grandfather" },
          { type: "mcq", q: "What is the plural of 'mi hermano'?", options: ["mi hermanos", "mis hermano", "mis hermanos", "míos hermanos"], a: "mis hermanos" },
          { type: "fill", q: "Daughter: ___", a: "hija" },
          { type: "mcq", q: "If someone says 'Tengo dos hermanas', they have:", options: ["Two brothers", "Two sisters", "Two parents", "Two friends"], a: "Two sisters" },
          { type: "mcq", q: "Which sentence means 'This is my father'?", options: ["Este es mi padre", "Esta es mi madre", "Mi padre es grande", "Tengo padre"], a: "Este es mi padre" },
          { type: "fill", q: "Friend (female): ___", a: "amiga" },
          { type: "mcq", q: "'Esposa' means:", options: ["Sister", "Daughter", "Wife", "Aunt"], a: "Wife" },
        ],
      },
      {
        id: 5,
        title: "Food & Dining",
        grammar: "'Quisiera' (I would like) is the polite way to order. Use 'la cuenta' to ask for the bill. In Spain, tapas are small shared dishes.",
        vocab: [
          { term: "agua", meaning: "water" },
          { term: "café", meaning: "coffee" },
          { term: "pan", meaning: "bread" },
          { term: "carne", meaning: "meat" },
          { term: "pollo", meaning: "chicken" },
          { term: "ensalada", meaning: "salad" },
          { term: "fruta", meaning: "fruit" },
          { term: "queso", meaning: "cheese" },
        ],
        phrases: [
          { term: "La cuenta, por favor", meaning: "The bill, please" },
          { term: "¿Qué recomienda?", meaning: "What do you recommend?" },
          { term: "Quisiera…", meaning: "I would like…" },
        ],
        quiz: [
          { type: "mcq", q: "You're at a Spanish restaurant and want to politely order. You start with:", options: ["Dame", "Quisiera", "Quiero ahora", "Necesito"], a: "Quisiera" },
          { type: "fill", q: "Water: ___", a: "agua" },
          { type: "mcq", q: "Done with your meal, you call the waiter and ask for:", options: ["la cuenta", "el menú", "la silla", "el pan"], a: "la cuenta" },
          { type: "mcq", q: "Which is a vegetarian-friendly dish?", options: ["pollo", "carne", "ensalada", "pescado"], a: "ensalada" },
          { type: "fill", q: "Bread: ___", a: "pan" },
          { type: "mcq", q: "'¿Qué recomienda?' means:", options: ["How much?", "What do you recommend?", "Where is it?", "Who are you?"], a: "What do you recommend?" },
          { type: "mcq", q: "'Pollo' is:", options: ["Beef", "Pork", "Chicken", "Fish"], a: "Chicken" },
          { type: "fill", q: "Cheese: ___", a: "queso" },
          { type: "mcq", q: "A friend says 'Me gusta la fruta.' They like:", options: ["Bread", "Cheese", "Fruit", "Coffee"], a: "Fruit" },
        ],
      },
      {
        id: 6,
        title: "Time & Calendar",
        grammar: "Tell the hour with 'Es la una' (1:00) or 'Son las…' (2+:00). Days of the week are masculine: el lunes. Spanish weeks start on Monday.",
        vocab: [
          { term: "lunes", meaning: "Monday" },
          { term: "martes", meaning: "Tuesday" },
          { term: "miércoles", meaning: "Wednesday" },
          { term: "jueves", meaning: "Thursday" },
          { term: "viernes", meaning: "Friday" },
          { term: "sábado / domingo", meaning: "Saturday / Sunday" },
          { term: "hoy / mañana / ayer", meaning: "today / tomorrow / yesterday" },
        ],
        phrases: [
          { term: "¿Qué hora es?", meaning: "What time is it?" },
          { term: "¿Qué día es hoy?", meaning: "What day is today?" },
          { term: "Son las tres", meaning: "It's 3 o'clock" },
        ],
        quiz: [
          { type: "mcq", q: "How do you say 'It's 1:00'?", options: ["Son las una", "Es la una", "Es uno", "La una es"], a: "Es la una" },
          { type: "fill", q: "Friday: ___", a: "viernes" },
          { type: "mcq", q: "Which day comes right after 'miércoles'?", options: ["martes", "viernes", "jueves", "lunes"], a: "jueves" },
          { type: "mcq", q: "'Hoy es sábado, mañana es ___':", options: ["viernes", "lunes", "domingo", "jueves"], a: "domingo" },
          { type: "fill", q: "Today: ___", a: "hoy" },
          { type: "mcq", q: "You ask 'What time is it?' in Spanish:", options: ["¿Qué día es?", "¿Cuánto cuesta?", "¿Qué hora es?", "¿Dónde está?"], a: "¿Qué hora es?" },
          { type: "mcq", q: "Why do you say 'Son las tres' but 'Es la una'?", options: ["Random rule", "Son is plural; the verb agrees with the number of hours", "Es means it's already late", "They're the same"], a: "Son is plural; the verb agrees with the number of hours" },
          { type: "fill", q: "Yesterday: ___", a: "ayer" },
          { type: "mcq", q: "'Son las cinco' means:", options: ["It's 1:00", "It's 5:00", "It's the fifth", "Five o'clock today"], a: "It's 5:00" },
        ],
      },
      {
        id: 7,
        title: "Travel & Directions",
        grammar: "Use 'estar' for location: ¿Dónde está…? (Where is…?). Common directions: a la izquierda (left), a la derecha (right), recto (straight).",
        vocab: [
          { term: "aeropuerto", meaning: "airport" },
          { term: "estación", meaning: "station" },
          { term: "hotel", meaning: "hotel" },
          { term: "baño", meaning: "bathroom" },
          { term: "calle", meaning: "street" },
          { term: "izquierda / derecha", meaning: "left / right" },
          { term: "cerca / lejos", meaning: "near / far" },
        ],
        phrases: [
          { term: "¿Dónde está el baño?", meaning: "Where is the bathroom?" },
          { term: "Siga recto", meaning: "Go straight" },
          { term: "A la derecha", meaning: "To the right" },
        ],
        quiz: [
          { type: "mcq", q: "You're lost and need to find the bathroom. You ask:", options: ["¿Cuánto cuesta?", "¿Dónde está el baño?", "¿Qué hora es?", "Mucho gusto"], a: "¿Dónde está el baño?" },
          { type: "fill", q: "Right (direction): a la ___", a: "derecha" },
          { type: "mcq", q: "Someone says 'Está muy cerca.' What does this mean?", options: ["It's very expensive", "It's very far", "It's very near", "It's very late"], a: "It's very near" },
          { type: "mcq", q: "You need to catch a train. You go to the:", options: ["aeropuerto", "estación", "hotel", "baño"], a: "estación" },
          { type: "fill", q: "Airport: ___", a: "aeropuerto" },
          { type: "mcq", q: "A local says 'Siga recto.' You should:", options: ["Turn left", "Turn right", "Go straight", "Go back"], a: "Go straight" },
          { type: "mcq", q: "Which question correctly asks 'Where is the hotel?'", options: ["¿Dónde está el hotel?", "¿Cuánto cuesta el hotel?", "¿Qué es el hotel?", "El hotel es"], a: "¿Dónde está el hotel?" },
          { type: "fill", q: "Left: ___", a: "izquierda" },
          { type: "mcq", q: "'Lejos' is the opposite of:", options: ["derecha", "cerca", "izquierda", "calle"], a: "cerca" },
        ],
      },
    ],
  },
  french: {
    name: "French",
    flag: "🇫🇷",
    native: "Français",
    lessons: [
      {
        id: 1,
        title: "Greetings & Politeness",
        grammar: "French uses formal (vous) and informal (tu) address. Always say Bonjour when entering a shop.",
        vocab: [
          { term: "Bonjour", meaning: "Hello / Good day" },
          { term: "Bonsoir", meaning: "Good evening" },
          { term: "Salut", meaning: "Hi (informal)" },
          { term: "Au revoir", meaning: "Goodbye" },
          { term: "Merci", meaning: "Thank you" },
          { term: "S'il vous plaît", meaning: "Please (formal)" },
        ],
        phrases: [
          { term: "Comment allez-vous?", meaning: "How are you? (formal)" },
          { term: "Je m'appelle…", meaning: "My name is…" },
          { term: "Enchanté(e)", meaning: "Pleased to meet you" },
        ],
        quiz: [
          { type: "mcq", q: "You enter a boutique in Paris. The first thing you should say is:", options: ["Merci", "Au revoir", "Bonjour", "Salut"], a: "Bonjour" },
          { type: "fill", q: "Good evening: ___", a: "bonsoir" },
          { type: "mcq", q: "You're at a formal dinner and want to ask how someone is. You say:", options: ["Salut, ça va?", "Comment allez-vous?", "Bonjour, merci", "Au revoir"], a: "Comment allez-vous?" },
          { type: "mcq", q: "Which word would you use to greet a close friend casually?", options: ["Bonjour", "Bonsoir", "Salut", "S'il vous plaît"], a: "Salut" },
          { type: "fill", q: "Goodbye: Au ___", a: "revoir" },
          { type: "mcq", q: "After introducing yourself, someone says 'Enchanté.' They mean:", options: ["Goodbye", "Thank you", "Pleased to meet you", "See you later"], a: "Pleased to meet you" },
          { type: "mcq", q: "'S'il vous plaît' is used when speaking to:", options: ["Close friends only", "Children only", "Someone formally / politely", "Pets"], a: "Someone formally / politely" },
          { type: "fill", q: "My name is…: Je m'___…", a: "appelle" },
          { type: "mcq", q: "You're speaking to your boss. Which form of 'you' should you use?", options: ["tu", "vous", "je", "il"], a: "vous" },
          { type: "mcq", q: "Which response fits: someone gives you a gift and you want to say thank you?", options: ["Au revoir", "Merci", "Bonjour", "Salut"], a: "Merci" },
        ],
      },
      {
        id: 2,
        title: "Numbers & Shopping",
        grammar: "French numbers 1–10: un, deux, trois… Sixty is soixante; seventy is soixante-dix.",
        vocab: [
          { term: "un / une", meaning: "one" },
          { term: "deux", meaning: "two" },
          { term: "trois", meaning: "three" },
          { term: "cinq", meaning: "five" },
          { term: "dix", meaning: "ten" },
        ],
        phrases: [
          { term: "C'est combien?", meaning: "How much is it?" },
          { term: "Je voudrais…", meaning: "I would like…" },
        ],
        quiz: [
          { type: "mcq", q: "You're at a café and want to order. You begin with:", options: ["C'est combien?", "Je voudrais…", "Au revoir", "Merci"], a: "Je voudrais…" },
          { type: "fill", q: "The number 3 in French: ___", a: "trois" },
          { type: "mcq", q: "A shopkeeper says 'C'est dix euros.' How much is the item?", options: ["2 euros", "3 euros", "5 euros", "10 euros"], a: "10 euros" },
          { type: "fill", q: "Five: ___", a: "cinq" },
          { type: "mcq", q: "The French word for 70 (soixante-dix) literally translates to:", options: ["Seven-ten", "Sixty-ten", "Seventy", "Fifty-twenty"], a: "Sixty-ten" },
          { type: "mcq", q: "You see a price tag and want to confirm the cost. You ask:", options: ["Bonjour?", "C'est combien?", "Comment?", "Merci?"], a: "C'est combien?" },
          { type: "fill", q: "Ten: ___", a: "dix" },
          { type: "mcq", q: "Which is the correct order: un, ___, trois?", options: ["cinq", "dix", "deux", "quatre"], a: "deux" },
          { type: "mcq", q: "'Je voudrais deux croissants' means:", options: ["I have two croissants", "I would like two croissants", "I see two croissants", "Give me two croissants"], a: "I would like two croissants" },
          { type: "fill", q: "Two: ___", a: "deux" },
        ],
      },
      {
        id: 3,
        title: "Common Verbs",
        grammar: "être (to be) and avoir (to have) are irregular. Je suis = I am; J'ai = I have.",
        vocab: [
          { term: "être", meaning: "to be" },
          { term: "avoir", meaning: "to have" },
          { term: "aller", meaning: "to go" },
          { term: "faire", meaning: "to do / make" },
          { term: "parler", meaning: "to speak" },
        ],
        phrases: [
          { term: "Je suis étudiant", meaning: "I am a student" },
          { term: "J'ai faim", meaning: "I am hungry (lit. I have hunger)" },
        ],
        quiz: [
          { type: "mcq", q: "In French, to say 'I am hungry,' you literally say 'I ___ hunger':", options: ["am", "have", "want", "see"], a: "have" },
          { type: "fill", q: "To be: ___", a: "être" },
          { type: "mcq", q: "Someone asks your occupation. You answer 'Je suis médecin.' What does 'suis' come from?", options: ["avoir", "aller", "être", "faire"], a: "être" },
          { type: "mcq", q: "Which two French verbs are irregular (don't follow standard patterns)?", options: ["parler and aller", "être and avoir", "faire and parler", "aller and parler"], a: "être and avoir" },
          { type: "fill", q: "To go: ___", a: "aller" },
          { type: "mcq", q: "'Je fais du sport' means:", options: ["I watch sports", "I do sports", "I have sports", "I go to sports"], a: "I do sports" },
          { type: "mcq", q: "Complete: 'Je ___ français' (I speak French)", options: ["suis", "ai", "parle", "fais"], a: "parle" },
          { type: "fill", q: "To have: ___", a: "avoir" },
          { type: "mcq", q: "'J'ai faim' uses 'avoir' because French expresses hunger as:", options: ["Being hungry", "Having hunger", "Going hungry", "Making hunger"], a: "Having hunger" },
          { type: "mcq", q: "Which verb means 'to do' or 'to make'?", options: ["aller", "parler", "faire", "être"], a: "faire" },
        ],
      },
      {
        id: 4,
        title: "Family & People",
        grammar: "French possessives agree with the gender/number of what is owned: mon père (m), ma mère (f), mes parents (pl). Before a feminine word starting with a vowel, use 'mon' (mon amie).",
        vocab: [
          { term: "mère", meaning: "mother" },
          { term: "père", meaning: "father" },
          { term: "frère / sœur", meaning: "brother / sister" },
          { term: "fils / fille", meaning: "son / daughter" },
          { term: "grand-père / grand-mère", meaning: "grandfather / grandmother" },
          { term: "ami / amie", meaning: "friend (m. / f.)" },
          { term: "mari / femme", meaning: "husband / wife" },
        ],
        phrases: [
          { term: "Tu as des frères et sœurs?", meaning: "Do you have siblings?" },
          { term: "Voici ma famille", meaning: "This is my family" },
          { term: "C'est mon père", meaning: "This is my father" },
        ],
        quiz: [
          { type: "mcq", q: "How do you say 'mother' in French?", options: ["père", "mère", "fille", "sœur"], a: "mère" },
          { type: "fill", q: "My father: ___ père", a: "mon" },
          { type: "mcq", q: "Even though 'amie' is feminine, before a vowel you use:", options: ["ma", "mon", "mes", "me"], a: "mon" },
          { type: "mcq", q: "Your friend says 'J'ai deux sœurs.' She has:", options: ["Two brothers", "Two sisters", "Two friends", "Two parents"], a: "Two sisters" },
          { type: "fill", q: "Daughter: ___", a: "fille" },
          { type: "mcq", q: "Which is the correct possessive for 'my parents'?", options: ["mon parents", "ma parents", "mes parents", "moi parents"], a: "mes parents" },
          { type: "fill", q: "Brother: ___", a: "frère" },
          { type: "mcq", q: "'Grand-père' means:", options: ["Brother", "Father", "Grandfather", "Uncle"], a: "Grandfather" },
          { type: "mcq", q: "Someone says 'Voici ma famille.' They are:", options: ["Saying goodbye", "Introducing their family", "Asking your age", "Ordering food"], a: "Introducing their family" },
        ],
      },
      {
        id: 5,
        title: "Food & Dining",
        grammar: "Partitive articles express 'some': du pain (some bread, m), de la viande (some meat, f), des frites (some fries, pl). 'L'addition' = the bill.",
        vocab: [
          { term: "pain", meaning: "bread" },
          { term: "fromage", meaning: "cheese" },
          { term: "vin", meaning: "wine" },
          { term: "eau", meaning: "water" },
          { term: "café", meaning: "coffee" },
          { term: "viande", meaning: "meat" },
          { term: "poulet", meaning: "chicken" },
          { term: "salade", meaning: "salad" },
        ],
        phrases: [
          { term: "L'addition, s'il vous plaît", meaning: "The bill, please" },
          { term: "Bon appétit", meaning: "Enjoy your meal" },
          { term: "Je voudrais…", meaning: "I would like…" },
        ],
        quiz: [
          { type: "mcq", q: "Before a French meal, people often say:", options: ["Au revoir", "Bonsoir", "Bon appétit", "L'addition"], a: "Bon appétit" },
          { type: "fill", q: "I would like some bread: Je voudrais ___ pain", a: "du" },
          { type: "mcq", q: "Which partitive article goes with feminine nouns?", options: ["du", "de la", "des", "le"], a: "de la" },
          { type: "mcq", q: "You finish dinner and want the check. You say:", options: ["Bon appétit", "L'addition, s'il vous plaît", "Bonjour", "Au revoir"], a: "L'addition, s'il vous plaît" },
          { type: "fill", q: "Water: ___", a: "eau" },
          { type: "mcq", q: "Which is a beverage?", options: ["pain", "fromage", "vin", "salade"], a: "vin" },
          { type: "fill", q: "Chicken: ___", a: "poulet" },
          { type: "mcq", q: "'Je voudrais du fromage' means:", options: ["I want bread", "I would like some cheese", "I have cheese", "Where is the cheese?"], a: "I would like some cheese" },
          { type: "mcq", q: "Partitive 'des' (some) is used for:", options: ["Masculine singular", "Feminine singular", "Plural nouns", "Verbs only"], a: "Plural nouns" },
        ],
      },
      {
        id: 6,
        title: "Time & Calendar",
        grammar: "Telling time: Il est une heure (1:00), Il est deux heures (2:00). Days and months are NOT capitalized in French: lundi, janvier.",
        vocab: [
          { term: "lundi", meaning: "Monday" },
          { term: "mardi", meaning: "Tuesday" },
          { term: "mercredi", meaning: "Wednesday" },
          { term: "jeudi", meaning: "Thursday" },
          { term: "vendredi", meaning: "Friday" },
          { term: "samedi / dimanche", meaning: "Saturday / Sunday" },
          { term: "aujourd'hui / demain / hier", meaning: "today / tomorrow / yesterday" },
        ],
        phrases: [
          { term: "Quelle heure est-il?", meaning: "What time is it?" },
          { term: "Quel jour sommes-nous?", meaning: "What day is it?" },
          { term: "Il est trois heures", meaning: "It's 3 o'clock" },
        ],
        quiz: [
          { type: "mcq", q: "Which is written correctly in French?", options: ["Lundi", "lundi", "LUNDI", "LunDi"], a: "lundi" },
          { type: "fill", q: "Friday: ___", a: "vendredi" },
          { type: "mcq", q: "How do you say 'It's 1 o'clock'?", options: ["Il est un heure", "Il est une heure", "C'est un", "Il est l'heure une"], a: "Il est une heure" },
          { type: "mcq", q: "'Aujourd'hui c'est mercredi, demain c'est ___':", options: ["mardi", "jeudi", "vendredi", "samedi"], a: "jeudi" },
          { type: "fill", q: "Today: ___", a: "aujourd'hui" },
          { type: "mcq", q: "You ask 'What time is it?' in French:", options: ["Quel jour?", "Quelle heure est-il?", "Combien?", "Où?"], a: "Quelle heure est-il?" },
          { type: "fill", q: "Yesterday: ___", a: "hier" },
          { type: "mcq", q: "Which day comes BEFORE 'jeudi'?", options: ["mardi", "mercredi", "vendredi", "lundi"], a: "mercredi" },
          { type: "mcq", q: "'Il est cinq heures' means:", options: ["It's the 5th", "It's 5 o'clock", "Five hours", "Five days"], a: "It's 5 o'clock" },
        ],
      },
      {
        id: 7,
        title: "Travel & Directions",
        grammar: "Use 'Où est…?' to ask 'Where is…?' Directions: à gauche (left), à droite (right), tout droit (straight ahead).",
        vocab: [
          { term: "aéroport", meaning: "airport" },
          { term: "gare", meaning: "train station" },
          { term: "hôtel", meaning: "hotel" },
          { term: "toilettes", meaning: "bathroom / toilets" },
          { term: "rue", meaning: "street" },
          { term: "gauche / droite", meaning: "left / right" },
          { term: "près / loin", meaning: "near / far" },
        ],
        phrases: [
          { term: "Où sont les toilettes?", meaning: "Where are the bathrooms?" },
          { term: "Tout droit", meaning: "Straight ahead" },
          { term: "À droite", meaning: "To the right" },
        ],
        quiz: [
          { type: "mcq", q: "You need to find the restroom at a café. You ask:", options: ["L'addition?", "Où sont les toilettes?", "Bonjour?", "Quelle heure?"], a: "Où sont les toilettes?" },
          { type: "fill", q: "Right: à ___", a: "droite" },
          { type: "mcq", q: "A local says 'Tout droit.' You should go:", options: ["Left", "Right", "Straight ahead", "Back"], a: "Straight ahead" },
          { type: "mcq", q: "Which place is for trains?", options: ["aéroport", "gare", "hôtel", "rue"], a: "gare" },
          { type: "fill", q: "Airport: ___", a: "aéroport" },
          { type: "mcq", q: "'Près' is the opposite of:", options: ["droite", "loin", "gauche", "rue"], a: "loin" },
          { type: "mcq", q: "Which question correctly asks 'Where is the hotel?'", options: ["Où est l'hôtel?", "Quel hôtel?", "L'hôtel ici", "Hôtel près?"], a: "Où est l'hôtel?" },
          { type: "fill", q: "Left: ___", a: "gauche" },
          { type: "mcq", q: "Your taxi driver says 'C'est loin.' This means:", options: ["It's close", "It's free", "It's far", "It's right here"], a: "It's far" },
        ],
      },
    ],
  },
  german: {
    name: "German",
    flag: "🇩🇪",
    native: "Deutsch",
    lessons: [
      {
        id: 1,
        title: "Greetings & Basics",
        grammar: "German capitalizes all nouns. Guten Tag is neutral-formal; Hallo is casual.",
        vocab: [
          { term: "Hallo", meaning: "Hello" },
          { term: "Guten Morgen", meaning: "Good morning" },
          { term: "Guten Tag", meaning: "Good day" },
          { term: "Gute Nacht", meaning: "Good night" },
          { term: "Danke", meaning: "Thank you" },
          { term: "Bitte", meaning: "Please / You're welcome" },
        ],
        phrases: [
          { term: "Wie heißen Sie?", meaning: "What is your name? (formal)" },
          { term: "Ich heiße…", meaning: "My name is…" },
          { term: "Freut mich", meaning: "Nice to meet you" },
        ],
        quiz: [
          { type: "mcq", q: "You arrive at a business meeting at 9 AM. You say:", options: ["Gute Nacht", "Guten Morgen", "Hallo, tschüss", "Guten Abend"], a: "Guten Morgen" },
          { type: "fill", q: "My name is…: Ich ___…", a: "heiße" },
          { type: "mcq", q: "Someone passes you the salt at dinner. You say:", options: ["Hallo", "Gute Nacht", "Danke", "Tschüss"], a: "Danke" },
          { type: "mcq", q: "'Bitte' can be used as a response to 'Danke.' In that context it means:", options: ["Please", "You're welcome", "Hello", "Sorry"], a: "You're welcome" },
          { type: "fill", q: "Good day: Guten ___", a: "tag", hint: "3 letters" },
          { type: "mcq", q: "You're at a formal event and want to ask someone's name. You say:", options: ["Wie heißen Sie?", "Hallo, ich bin…", "Guten Morgen", "Freut mich"], a: "Wie heißen Sie?" },
          { type: "mcq", q: "After introducing yourselves, you shake hands and say:", options: ["Danke", "Gute Nacht", "Freut mich", "Bitte"], a: "Freut mich" },
          { type: "fill", q: "Thank you: ___", a: "danke" },
          { type: "mcq", q: "It's 11 PM and you're heading to bed. You say:", options: ["Guten Morgen", "Guten Tag", "Gute Nacht", "Hallo"], a: "Gute Nacht" },
          { type: "mcq", q: "Which greeting is most neutral and works anytime during the day?", options: ["Guten Morgen", "Gute Nacht", "Guten Tag", "Guten Abend"], a: "Guten Tag" },
        ],
      },
      {
        id: 2,
        title: "Numbers & Time",
        grammar: "German numbers: eins, zwei, drei… Uhr means o'clock (Es ist drei Uhr).",
        vocab: [
          { term: "eins", meaning: "one" },
          { term: "zwei", meaning: "two" },
          { term: "drei", meaning: "three" },
          { term: "fünf", meaning: "five" },
          { term: "zehn", meaning: "ten" },
        ],
        phrases: [
          { term: "Wie viel kostet das?", meaning: "How much does that cost?" },
          { term: "Wie spät ist es?", meaning: "What time is it?" },
        ],
        quiz: [
          { type: "mcq", q: "You want to know the time. You ask:", options: ["Wie heißen Sie?", "Wie spät ist es?", "Wie viel kostet das?", "Guten Tag?"], a: "Wie spät ist es?" },
          { type: "fill", q: "Three: ___", a: "drei" },
          { type: "mcq", q: "Someone says 'Es ist fünf Uhr.' What time is it?", options: ["3 o'clock", "5 o'clock", "10 o'clock", "2 o'clock"], a: "5 o'clock" },
          { type: "mcq", q: "You're shopping and want to ask the price. You say:", options: ["Wie spät ist es?", "Wie heißen Sie?", "Wie viel kostet das?", "Danke schön"], a: "Wie viel kostet das?" },
          { type: "fill", q: "Ten: ___", a: "zehn" },
          { type: "mcq", q: "Put these in order: drei, eins, fünf, zwei", options: ["eins, zwei, drei, fünf", "zwei, drei, eins, fünf", "fünf, drei, zwei, eins", "drei, eins, fünf, zwei"], a: "eins, zwei, drei, fünf" },
          { type: "fill", q: "Five: ___", a: "fünf" },
          { type: "mcq", q: "The word 'Uhr' in German means:", options: ["Hour", "O'clock / Clock", "Time zone", "Minute"], a: "O'clock / Clock" },
          { type: "mcq", q: "A shopkeeper says 'Das kostet zwei Euro.' How much is it?", options: ["1 euro", "2 euros", "3 euros", "5 euros"], a: "2 euros" },
          { type: "fill", q: "Two: ___", a: "zwei" },
        ],
      },
      {
        id: 3,
        title: "Common Verbs",
        grammar: "German verbs conjugate by subject: ich habe, du hast, er/sie/es hat. 'Sein' (to be) and 'haben' (to have) are irregular and used everywhere.",
        vocab: [
          { term: "sein", meaning: "to be" },
          { term: "haben", meaning: "to have" },
          { term: "gehen", meaning: "to go" },
          { term: "kommen", meaning: "to come" },
          { term: "sprechen", meaning: "to speak" },
          { term: "essen", meaning: "to eat" },
          { term: "trinken", meaning: "to drink" },
        ],
        phrases: [
          { term: "Ich habe Hunger", meaning: "I am hungry (lit. I have hunger)" },
          { term: "Ich gehe nach Hause", meaning: "I am going home" },
          { term: "Sprechen Sie Englisch?", meaning: "Do you speak English?" },
        ],
        quiz: [
          { type: "mcq", q: "Like French, German expresses hunger with 'to have.' 'Ich habe Hunger' literally means:", options: ["I am hungry", "I have hunger", "I want food", "I eat now"], a: "I have hunger" },
          { type: "fill", q: "To be: ___", a: "sein" },
          { type: "mcq", q: "'Du ___ Wasser' (You drink water). Which form fits?", options: ["trinkt", "trinke", "trinkst", "trinken"], a: "trinkst" },
          { type: "mcq", q: "You meet a German speaker and want to know if they speak English. You ask:", options: ["Sprechen Sie Englisch?", "Was ist das?", "Ich gehe nach Hause", "Ich habe Hunger"], a: "Sprechen Sie Englisch?" },
          { type: "fill", q: "To eat: ___", a: "essen" },
          { type: "mcq", q: "Which two German verbs are the most common and irregular?", options: ["gehen and kommen", "sein and haben", "essen and trinken", "sprechen and gehen"], a: "sein and haben" },
          { type: "mcq", q: "'Ich gehe nach Hause' means:", options: ["I have a house", "I am going home", "I eat at home", "I see a house"], a: "I am going home" },
          { type: "fill", q: "To drink: ___", a: "trinken" },
          { type: "mcq", q: "If 'ich bin' means 'I am', then 'du ___' means 'you are':", options: ["ist", "sind", "bist", "seid"], a: "bist" },
        ],
      },
      {
        id: 4,
        title: "Family & People",
        grammar: "Possessives change with gender and case: mein Vater (my father, m), meine Mutter (my mother, f), meine Eltern (my parents, pl).",
        vocab: [
          { term: "Mutter", meaning: "mother" },
          { term: "Vater", meaning: "father" },
          { term: "Bruder / Schwester", meaning: "brother / sister" },
          { term: "Sohn / Tochter", meaning: "son / daughter" },
          { term: "Großvater / Großmutter", meaning: "grandfather / grandmother" },
          { term: "Freund / Freundin", meaning: "friend (m. / f.)" },
          { term: "Eltern", meaning: "parents" },
        ],
        phrases: [
          { term: "Das ist meine Familie", meaning: "This is my family" },
          { term: "Hast du Geschwister?", meaning: "Do you have siblings?" },
          { term: "Das ist mein Bruder", meaning: "This is my brother" },
        ],
        quiz: [
          { type: "mcq", q: "How do you say 'mother' in German?", options: ["Vater", "Mutter", "Tochter", "Schwester"], a: "Mutter" },
          { type: "fill", q: "My father: ___ Vater", a: "mein" },
          { type: "mcq", q: "Why is 'Mutter' capitalized?", options: ["It's a name", "All German nouns are capitalized", "Only female words are capitalized", "It's a typo"], a: "All German nouns are capitalized" },
          { type: "mcq", q: "'Meine Schwester' means:", options: ["My brother", "My sister", "My mother", "My daughter"], a: "My sister" },
          { type: "fill", q: "My mother: ___ Mutter", a: "meine" },
          { type: "mcq", q: "Someone asks 'Hast du Geschwister?' They want to know if you have:", options: ["Children", "Siblings", "Pets", "A car"], a: "Siblings" },
          { type: "fill", q: "Son: ___", a: "sohn" },
          { type: "mcq", q: "'Großmutter' refers to your:", options: ["Aunt", "Older sister", "Grandmother", "Stepmother"], a: "Grandmother" },
          { type: "mcq", q: "Which possessive is correct with feminine nouns like 'Schwester'?", options: ["mein", "meine", "meines", "meinem"], a: "meine" },
        ],
      },
      {
        id: 5,
        title: "Food & Dining",
        grammar: "Articles change with case. Nominative: das Brot. Accusative (direct object): Ich esse das Brot. 'Ich möchte' is polite 'I would like'.",
        vocab: [
          { term: "Brot", meaning: "bread" },
          { term: "Wasser", meaning: "water" },
          { term: "Bier", meaning: "beer" },
          { term: "Wein", meaning: "wine" },
          { term: "Käse", meaning: "cheese" },
          { term: "Fleisch", meaning: "meat" },
          { term: "Apfel", meaning: "apple" },
          { term: "Suppe", meaning: "soup" },
        ],
        phrases: [
          { term: "Die Rechnung, bitte", meaning: "The bill, please" },
          { term: "Ich möchte…", meaning: "I would like…" },
          { term: "Guten Appetit", meaning: "Enjoy your meal" },
        ],
        quiz: [
          { type: "mcq", q: "You want to order politely in a German restaurant. You say:", options: ["Ich will", "Ich möchte…", "Gib mir", "Brauchen"], a: "Ich möchte…" },
          { type: "fill", q: "Water: ___", a: "wasser" },
          { type: "mcq", q: "Before eating, Germans often say:", options: ["Auf Wiedersehen", "Guten Appetit", "Danke", "Hallo"], a: "Guten Appetit" },
          { type: "mcq", q: "After dinner, you ask the server for:", options: ["die Rechnung", "das Brot", "den Apfel", "die Suppe"], a: "die Rechnung" },
          { type: "fill", q: "Bread: ___", a: "brot" },
          { type: "mcq", q: "Which is a vegetarian option?", options: ["Fleisch", "Käse", "Bier", "Wein"], a: "Käse" },
          { type: "fill", q: "Beer: ___", a: "bier" },
          { type: "mcq", q: "'Ich esse den Apfel' uses 'den' instead of 'der' because 'Apfel' is:", options: ["Plural", "Feminine", "The direct object (accusative)", "Capitalized"], a: "The direct object (accusative)" },
          { type: "mcq", q: "'Suppe' means:", options: ["Supper", "Soup", "Salad", "Sandwich"], a: "Soup" },
        ],
      },
      {
        id: 6,
        title: "Travel & Directions",
        grammar: "Use 'Wo ist…?' to ask 'Where is…?' Directions: links (left), rechts (right), geradeaus (straight ahead).",
        vocab: [
          { term: "Bahnhof", meaning: "train station" },
          { term: "Flughafen", meaning: "airport" },
          { term: "Hotel", meaning: "hotel" },
          { term: "Toilette", meaning: "toilet / bathroom" },
          { term: "Straße", meaning: "street" },
          { term: "links / rechts", meaning: "left / right" },
          { term: "geradeaus", meaning: "straight ahead" },
        ],
        phrases: [
          { term: "Wo ist die Toilette?", meaning: "Where is the bathroom?" },
          { term: "Gehen Sie geradeaus", meaning: "Go straight ahead" },
          { term: "Nach rechts", meaning: "To the right" },
        ],
        quiz: [
          { type: "mcq", q: "You're in Berlin and need a bathroom. You ask:", options: ["Wie spät ist es?", "Wo ist die Toilette?", "Wie viel kostet das?", "Wie heißen Sie?"], a: "Wo ist die Toilette?" },
          { type: "fill", q: "Right: ___", a: "rechts" },
          { type: "mcq", q: "A local says 'Gehen Sie geradeaus.' You should:", options: ["Turn around", "Go straight", "Turn left", "Wait"], a: "Go straight" },
          { type: "mcq", q: "You're catching a train to Munich. You go to the:", options: ["Flughafen", "Hotel", "Bahnhof", "Straße"], a: "Bahnhof" },
          { type: "fill", q: "Airport: ___", a: "flughafen" },
          { type: "mcq", q: "Which question correctly asks 'Where is the hotel?'", options: ["Wo ist das Hotel?", "Was ist das Hotel?", "Wer ist das Hotel?", "Wie Hotel?"], a: "Wo ist das Hotel?" },
          { type: "fill", q: "Left: ___", a: "links" },
          { type: "mcq", q: "'Straße' begins with a capital letter because it is a:", options: ["Verb", "Noun (all German nouns are capitalized)", "Question word", "Adjective"], a: "Noun (all German nouns are capitalized)" },
          { type: "mcq", q: "Which place would you go to fly internationally?", options: ["Bahnhof", "Flughafen", "Hotel", "Toilette"], a: "Flughafen" },
        ],
      },
    ],
  },
  japanese: {
    name: "Japanese",
    flag: "🇯🇵",
    native: "日本語",
    lessons: [
      {
        id: 1,
        title: "Greetings & Courtesy",
        grammar: "Japanese has polite (です/ます) and casual forms. Bowing accompanies greetings. は is pronounced 'wa' as a particle.",
        vocab: [
          { term: "こんにちは", meaning: "Hello (afternoon)" },
          { term: "おはよう", meaning: "Good morning" },
          { term: "こんばんは", meaning: "Good evening" },
          { term: "さようなら", meaning: "Goodbye" },
          { term: "ありがとう", meaning: "Thank you" },
          { term: "すみません", meaning: "Excuse me / Sorry" },
        ],
        phrases: [
          { term: "はじめまして", meaning: "Nice to meet you" },
          { term: "お元気ですか", meaning: "How are you? (polite)" },
          { term: "よろしくお願いします", meaning: "Please treat me well (common intro)" },
        ],
        quiz: [
          { type: "mcq", q: "It's 2 PM and you greet your neighbor. You say:", options: ["おはよう", "こんにちは", "こんばんは", "さようなら"], a: "こんにちは" },
          { type: "mcq", q: "You're meeting a new colleague for the first time. After your name, you say:", options: ["さようなら", "すみません", "はじめまして", "おはよう"], a: "はじめまして" },
          { type: "mcq", q: "You want to get a waiter's attention at a restaurant. You say:", options: ["ありがとう", "こんにちは", "すみません", "さようなら"], a: "すみません" },
          { type: "mcq", q: "The particle は in 'こんにちは' is pronounced:", options: ["ha", "wa", "ka", "sa"], a: "wa" },
          { type: "mcq", q: "After someone does you a favor, you say:", options: ["すみません", "さようなら", "ありがとう", "おはよう"], a: "ありがとう" },
          { type: "mcq", q: "It's early morning at the office. You greet your coworker with:", options: ["こんばんは", "さようなら", "こんにちは", "おはようございます"], a: "おはようございます" },
          { type: "mcq", q: "'お元気ですか' is equivalent to which English phrase?", options: ["What's your name?", "How are you?", "Where are you going?", "What time is it?"], a: "How are you?" },
          { type: "mcq", q: "At the end of a self-introduction, Japanese people often say:", options: ["さようなら", "すみません", "よろしくお願いします", "ありがとう"], a: "よろしくお願いします" },
          { type: "mcq", q: "You're leaving a friend's house for the last time before moving away. You say:", options: ["おはよう", "こんにちは", "すみません", "さようなら"], a: "さようなら" },
          { type: "mcq", q: "Which is more polite: 'ありがとう' or 'ありがとうございます'?", options: ["ありがとう", "ありがとうございます", "They are the same", "Neither is polite"], a: "ありがとうございます" },
        ],
      },
      {
        id: 2,
        title: "Numbers & Counters",
        grammar: "Japanese uses counters after numbers (一つ hitotsu = one thing). Native numbers 1–5: 一, 二, 三, 四, 五.",
        vocab: [
          { term: "一 (いち)", meaning: "one" },
          { term: "二 (に)", meaning: "two" },
          { term: "三 (さん)", meaning: "three" },
          { term: "四 (よん/し)", meaning: "four" },
          { term: "五 (ご)", meaning: "five" },
          { term: "十 (じゅう)", meaning: "ten" },
        ],
        phrases: [
          { term: "いくらですか", meaning: "How much is it?" },
          { term: "〜をください", meaning: "Please give me…" },
        ],
        quiz: [
          { type: "mcq", q: "You're at a convenience store and want to know the price. You ask:", options: ["すみません", "ありがとう", "いくらですか", "こんにちは"], a: "いくらですか" },
          { type: "mcq", q: "The kanji 三 represents which number?", options: ["One", "Two", "Three", "Five"], a: "Three" },
          { type: "mcq", q: "Japanese uses special words after numbers when counting objects. These are called:", options: ["Particles", "Counters", "Conjugations", "Honorifics"], a: "Counters" },
          { type: "mcq", q: "You want to order 2 coffees. You say 'コーヒーを二つください.' What does '二つ' mean?", options: ["One (thing)", "Two (things)", "Three (things)", "Five (things)"], a: "Two (things)" },
          { type: "mcq", q: "The number 四 has two readings: よん and し. Which reading is generally avoided because it sounds like 'death'?", options: ["よん", "し", "Both are fine", "Neither"], a: "し" },
          { type: "mcq", q: "What does '〜をください' mean?", options: ["How much?", "Please give me…", "Excuse me", "Thank you"], a: "Please give me…" },
          { type: "mcq", q: "The kanji 十 (じゅう) represents:", options: ["Five", "Seven", "Ten", "One hundred"], a: "Ten" },
          { type: "mcq", q: "Put these in numerical order: 五, 二, 四, 一", options: ["一, 二, 四, 五", "五, 四, 二, 一", "二, 一, 五, 四", "一, 四, 二, 五"], a: "一, 二, 四, 五" },
          { type: "mcq", q: "You hand money to a cashier and they give you change. You say:", options: ["いくらですか", "ありがとうございます", "すみません", "さようなら"], a: "ありがとうございます" },
          { type: "mcq", q: "What is 五 + 五 in Japanese?", options: ["五 (ご)", "十 (じゅう)", "二 (に)", "三 (さん)"], a: "十 (じゅう)" },
        ],
      },
      {
        id: 3,
        title: "Common Verbs",
        grammar: "Verbs come at the end of sentences. Polite forms end in ます (tabemasu = eat). Dictionary forms are used for casual speech. The particle を marks direct objects.",
        vocab: [
          { term: "食べる (たべる)", meaning: "to eat" },
          { term: "飲む (のむ)", meaning: "to drink" },
          { term: "行く (いく)", meaning: "to go" },
          { term: "来る (くる)", meaning: "to come" },
          { term: "見る (みる)", meaning: "to see / watch" },
          { term: "読む (よむ)", meaning: "to read" },
          { term: "する", meaning: "to do" },
        ],
        phrases: [
          { term: "寿司を食べます", meaning: "I eat sushi" },
          { term: "学校へ行きます", meaning: "I go to school" },
          { term: "本を読みます", meaning: "I read a book" },
        ],
        quiz: [
          { type: "mcq", q: "In a Japanese sentence, the verb typically comes:", options: ["First", "Second", "In the middle", "Last"], a: "Last" },
          { type: "mcq", q: "Which ending makes a verb polite?", options: ["ます", "だ", "の", "に"], a: "ます" },
          { type: "mcq", q: "'寿司を食べます' means:", options: ["I drink sushi", "I eat sushi", "I make sushi", "I see sushi"], a: "I eat sushi" },
          { type: "mcq", q: "The particle を (wo) marks:", options: ["The subject", "The topic", "The direct object", "The destination"], a: "The direct object" },
          { type: "mcq", q: "'飲む' means:", options: ["to eat", "to drink", "to go", "to read"], a: "to drink" },
          { type: "mcq", q: "Which verb means 'to go'?", options: ["来る", "見る", "行く", "する"], a: "行く" },
          { type: "mcq", q: "'本を読みます' is in which form?", options: ["Casual", "Polite (-masu)", "Past tense", "Negative"], a: "Polite (-masu)" },
          { type: "mcq", q: "Polite form of 食べる (to eat) is:", options: ["食べた", "食べない", "食べます", "食べて"], a: "食べます" },
          { type: "mcq", q: "To say 'I do my homework,' which verb do you need?", options: ["行く", "する", "来る", "見る"], a: "する" },
        ],
      },
      {
        id: 4,
        title: "Family & People",
        grammar: "Japanese uses different terms for your own family vs someone else's. 母 (haha) = my mother. お母さん (okaasan) = your/their mother — more polite when referring to others.",
        vocab: [
          { term: "家族 (かぞく)", meaning: "family" },
          { term: "父 (ちち) / お父さん", meaning: "father (mine / theirs)" },
          { term: "母 (はは) / お母さん", meaning: "mother (mine / theirs)" },
          { term: "兄 (あに) / 姉 (あね)", meaning: "older brother / older sister" },
          { term: "弟 (おとうと) / 妹 (いもうと)", meaning: "younger brother / younger sister" },
          { term: "友達 (ともだち)", meaning: "friend" },
        ],
        phrases: [
          { term: "家族は何人ですか?", meaning: "How many people are in your family?" },
          { term: "これは私の家族です", meaning: "This is my family" },
          { term: "兄弟がいますか?", meaning: "Do you have siblings?" },
        ],
        quiz: [
          { type: "mcq", q: "When talking about YOUR OWN mother, you say:", options: ["お母さん", "母", "母さま", "ママさん"], a: "母" },
          { type: "mcq", q: "When politely talking about SOMEONE ELSE'S mother, you say:", options: ["母", "お母さん", "私の母", "母です"], a: "お母さん" },
          { type: "mcq", q: "'家族' means:", options: ["School", "Friend", "Family", "Country"], a: "Family" },
          { type: "mcq", q: "Japanese distinguishes OLDER and YOUNGER siblings. Which is OLDER brother?", options: ["弟", "兄", "姉", "妹"], a: "兄" },
          { type: "mcq", q: "'妹' (imouto) means:", options: ["older sister", "younger sister", "older brother", "mother"], a: "younger sister" },
          { type: "mcq", q: "How do you say 'friend' in Japanese?", options: ["家族", "兄弟", "友達", "先生"], a: "友達" },
          { type: "mcq", q: "Someone asks '家族は何人ですか?' What do they want to know?", options: ["Your age", "Where you live", "How many family members you have", "Your job"], a: "How many family members you have" },
          { type: "mcq", q: "Which kanji means 'father' (your own)?", options: ["母", "父", "兄", "妹"], a: "父" },
          { type: "mcq", q: "Why does Japanese have words like 母 vs お母さん?", options: ["They mean different relatives", "Politeness changes when referring to your own vs others' family", "One is plural", "One is only written"], a: "Politeness changes when referring to your own vs others' family" },
        ],
      },
      {
        id: 5,
        title: "Food & Dining",
        grammar: "Say いただきます (itadakimasu) before eating and ごちそうさま (gochisousama) after. Express likes with 〜が好きです (ga suki desu).",
        vocab: [
          { term: "ご飯 (ごはん)", meaning: "rice / meal" },
          { term: "寿司 (すし)", meaning: "sushi" },
          { term: "ラーメン", meaning: "ramen" },
          { term: "水 (みず)", meaning: "water" },
          { term: "お茶 (おちゃ)", meaning: "tea" },
          { term: "肉 (にく)", meaning: "meat" },
          { term: "魚 (さかな)", meaning: "fish" },
          { term: "パン", meaning: "bread" },
        ],
        phrases: [
          { term: "いただきます", meaning: "Said before eating (lit. 'I humbly receive')" },
          { term: "ごちそうさまでした", meaning: "Said after eating ('That was a feast')" },
          { term: "お会計お願いします", meaning: "The bill, please" },
        ],
        quiz: [
          { type: "mcq", q: "Before starting a meal in Japan, you say:", options: ["ありがとう", "いただきます", "ごちそうさま", "さようなら"], a: "いただきます" },
          { type: "mcq", q: "After finishing a meal, you say:", options: ["いただきます", "ごちそうさまでした", "こんにちは", "すみません"], a: "ごちそうさまでした" },
          { type: "mcq", q: "'寿司が好きです' means:", options: ["I made sushi", "I like sushi", "I see sushi", "I don't like sushi"], a: "I like sushi" },
          { type: "mcq", q: "The word 'ご飯' can mean either:", options: ["Rice or meal", "Tea or water", "Bread or sushi", "Lunch or dinner"], a: "Rice or meal" },
          { type: "mcq", q: "How do you say 'water' in Japanese?", options: ["お茶", "ご飯", "水", "肉"], a: "水" },
          { type: "mcq", q: "Which dish is a Japanese noodle soup?", options: ["寿司", "ラーメン", "パン", "ご飯"], a: "ラーメン" },
          { type: "mcq", q: "You finished eating and want the bill. You say:", options: ["いただきます", "ごちそうさま", "お会計お願いします", "ありがとう"], a: "お会計お願いします" },
          { type: "mcq", q: "Which option is most vegetarian-friendly?", options: ["肉", "魚", "パン", "鶏肉"], a: "パン" },
          { type: "mcq", q: "To say 'I like fish', you say:", options: ["魚を食べます", "魚が好きです", "魚は水です", "魚を見ます"], a: "魚が好きです" },
        ],
      },
      {
        id: 6,
        title: "Travel & Places",
        grammar: "Particle へ marks destination (学校へ行きます). 〜はどこですか? means 'Where is ___?' Use 右 (right), 左 (left), まっすぐ (straight).",
        vocab: [
          { term: "駅 (えき)", meaning: "station" },
          { term: "空港 (くうこう)", meaning: "airport" },
          { term: "ホテル", meaning: "hotel" },
          { term: "トイレ", meaning: "toilet / bathroom" },
          { term: "銀行 (ぎんこう)", meaning: "bank" },
          { term: "右 (みぎ) / 左 (ひだり)", meaning: "right / left" },
          { term: "まっすぐ", meaning: "straight" },
        ],
        phrases: [
          { term: "トイレはどこですか?", meaning: "Where is the bathroom?" },
          { term: "まっすぐ行ってください", meaning: "Please go straight" },
          { term: "駅へ行きます", meaning: "I'm going to the station" },
        ],
        quiz: [
          { type: "mcq", q: "You're in Tokyo and need to find a bathroom. You ask:", options: ["これは何ですか?", "トイレはどこですか?", "いくらですか?", "いただきます"], a: "トイレはどこですか?" },
          { type: "mcq", q: "Which particle marks direction (toward a destination)?", options: ["は", "を", "へ", "の"], a: "へ" },
          { type: "mcq", q: "A local says 'まっすぐ行ってください.' You should:", options: ["Turn left", "Turn right", "Go straight", "Stop"], a: "Go straight" },
          { type: "mcq", q: "Which place would you go to catch a train?", options: ["空港", "ホテル", "駅", "銀行"], a: "駅" },
          { type: "mcq", q: "'右' means:", options: ["left", "right", "front", "back"], a: "right" },
          { type: "mcq", q: "You want to fly to Osaka. You go to the:", options: ["駅", "銀行", "空港", "ホテル"], a: "空港" },
          { type: "mcq", q: "Which sentence asks 'Where is the hotel?'", options: ["ホテルはどこですか?", "ホテルは何ですか?", "ホテルへ行きます", "ホテルですか?"], a: "ホテルはどこですか?" },
          { type: "mcq", q: "'銀行' means:", options: ["restaurant", "bank", "hospital", "school"], a: "bank" },
          { type: "mcq", q: "'左' means:", options: ["right", "left", "down", "up"], a: "left" },
        ],
      },
    ],
  },
  italian: {
    name: "Italian",
    flag: "🇮🇹",
    native: "Italiano",
    lessons: [
      {
        id: 1,
        title: "Greetings & Introductions",
        grammar: "Italian vowels are clear and open. Lei is formal 'you'; tu is informal.",
        vocab: [
          { term: "Ciao", meaning: "Hi / Bye (informal)" },
          { term: "Buongiorno", meaning: "Good morning / day" },
          { term: "Buonasera", meaning: "Good evening" },
          { term: "Arrivederci", meaning: "Goodbye" },
          { term: "Grazie", meaning: "Thank you" },
          { term: "Prego", meaning: "You're welcome / Please" },
        ],
        phrases: [
          { term: "Come ti chiami?", meaning: "What is your name?" },
          { term: "Mi chiamo…", meaning: "My name is…" },
          { term: "Piacere", meaning: "Pleased to meet you" },
        ],
        quiz: [
          { type: "mcq", q: "You walk into an Italian office at 10 AM. You greet the receptionist with:", options: ["Ciao", "Buonasera", "Buongiorno", "Arrivederci"], a: "Buongiorno" },
          { type: "fill", q: "My name is…: Mi ___…", a: "chiamo" },
          { type: "mcq", q: "A waiter brings your food. You say:", options: ["Arrivederci", "Grazie", "Buonasera", "Ciao"], a: "Grazie" },
          { type: "mcq", q: "You're speaking to an older person you've just met. You should use:", options: ["tu", "Lei", "io", "noi"], a: "Lei" },
          { type: "fill", q: "Goodbye (formal): ___", a: "arrivederci" },
          { type: "mcq", q: "Someone thanks you for holding the door. You respond with:", options: ["Grazie", "Ciao", "Prego", "Buongiorno"], a: "Prego" },
          { type: "mcq", q: "You meet someone new and they say 'Piacere.' They mean:", options: ["Goodbye", "Thank you", "Pleased to meet you", "You're welcome"], a: "Pleased to meet you" },
          { type: "fill", q: "Good evening: ___", a: "buonasera" },
          { type: "mcq", q: "'Ciao' is unique because it can mean both:", options: ["Please and thank you", "Hello and goodbye", "Yes and no", "Good morning and good night"], a: "Hello and goodbye" },
          { type: "mcq", q: "Someone asks 'Come ti chiami?' What information do they want?", options: ["Your age", "Your name", "Your nationality", "Your job"], a: "Your name" },
        ],
      },
      {
        id: 2,
        title: "Essential Verbs",
        grammar: "Verbs end in -are, -ere, -ire. Parlare (to speak): parlo, parli, parla…",
        vocab: [
          { term: "essere", meaning: "to be" },
          { term: "avere", meaning: "to have" },
          { term: "parlare", meaning: "to speak" },
          { term: "mangiare", meaning: "to eat" },
          { term: "andare", meaning: "to go" },
        ],
        phrases: [
          { term: "Sono di Roma", meaning: "I'm from Rome" },
          { term: "Ho fame", meaning: "I'm hungry" },
        ],
        quiz: [
          { type: "mcq", q: "Someone asks where you're from. You say 'Sono di Milano.' The verb 'sono' comes from:", options: ["avere", "andare", "essere", "parlare"], a: "essere" },
          { type: "fill", q: "To eat: ___", a: "mangiare" },
          { type: "mcq", q: "Like French, Italian expresses hunger using 'to have.' 'Ho fame' literally means:", options: ["I am hunger", "I have hunger", "I feel hunger", "I go hunger"], a: "I have hunger" },
          { type: "mcq", q: "Italian verbs are grouped by their endings. Which are the three groups?", options: ["-ar, -er, -ir", "-are, -ere, -ire", "-are, -ore, -ure", "-are, -ire, -ure"], a: "-are, -ere, -ire" },
          { type: "fill", q: "To speak: ___", a: "parlare" },
          { type: "mcq", q: "To conjugate 'parlare' for 'I', you change it to:", options: ["parli", "parla", "parlo", "parlano"], a: "parlo" },
          { type: "mcq", q: "You're at a train station and need to go to Florence. Which verb describes your action?", options: ["essere", "avere", "parlare", "andare"], a: "andare" },
          { type: "fill", q: "To have: ___", a: "avere" },
          { type: "mcq", q: "Which sentence means 'I speak Italian'?", options: ["Ho italiano", "Sono italiano", "Parlo italiano", "Mangio italiano"], a: "Parlo italiano" },
          { type: "mcq", q: "The verb 'essere' is irregular, meaning:", options: ["It follows standard conjugation rules", "It doesn't follow the regular -ere pattern", "It's never used", "It's only used in writing"], a: "It doesn't follow the regular -ere pattern" },
        ],
      },
      {
        id: 3,
        title: "Numbers & Shopping",
        grammar: "Italian numbers 1-10: uno, due, tre, quattro, cinque, sei, sette, otto, nove, dieci. 'Quanto costa?' asks the price.",
        vocab: [
          { term: "uno / due / tre", meaning: "one / two / three" },
          { term: "quattro / cinque", meaning: "four / five" },
          { term: "sei / sette / otto", meaning: "six / seven / eight" },
          { term: "nove / dieci", meaning: "nine / ten" },
          { term: "venti", meaning: "twenty" },
          { term: "cento", meaning: "one hundred" },
        ],
        phrases: [
          { term: "Quanto costa?", meaning: "How much does it cost?" },
          { term: "Vorrei…", meaning: "I would like…" },
          { term: "Sono dieci euro", meaning: "It's ten euros" },
        ],
        quiz: [
          { type: "mcq", q: "You're shopping in Rome and want to know a price. You ask:", options: ["Come stai?", "Quanto costa?", "Dov'è?", "Che cosa?"], a: "Quanto costa?" },
          { type: "fill", q: "Five: ___", a: "cinque" },
          { type: "mcq", q: "A vendor says 'Sono otto euro.' How much do you owe?", options: ["2 euros", "5 euros", "8 euros", "10 euros"], a: "8 euros" },
          { type: "mcq", q: "Put these in order: sette, due, cinque, nove", options: ["due, cinque, sette, nove", "nove, sette, cinque, due", "cinque, due, sette, nove", "due, sette, cinque, nove"], a: "due, cinque, sette, nove" },
          { type: "fill", q: "Ten: ___", a: "dieci" },
          { type: "mcq", q: "What is 'venti'?", options: ["12", "15", "20", "25"], a: "20" },
          { type: "mcq", q: "Which is the polite way to say 'I would like'?", options: ["Voglio", "Vorrei", "Mi dia", "Datemi"], a: "Vorrei" },
          { type: "fill", q: "Three: ___", a: "tre" },
          { type: "mcq", q: "'Cento' is:", options: ["10", "50", "100", "1000"], a: "100" },
        ],
      },
      {
        id: 4,
        title: "Family & People",
        grammar: "Italian possessives normally use the article (il mio libro). With singular, unmodified family members, drop the article: mio padre, mia madre. Use the article in plural or with adjectives: i miei fratelli.",
        vocab: [
          { term: "madre / padre", meaning: "mother / father" },
          { term: "fratello / sorella", meaning: "brother / sister" },
          { term: "figlio / figlia", meaning: "son / daughter" },
          { term: "nonno / nonna", meaning: "grandfather / grandmother" },
          { term: "amico / amica", meaning: "friend (m. / f.)" },
          { term: "marito / moglie", meaning: "husband / wife" },
        ],
        phrases: [
          { term: "Hai fratelli?", meaning: "Do you have siblings?" },
          { term: "Questa è la mia famiglia", meaning: "This is my family" },
          { term: "Mia madre si chiama Anna", meaning: "My mother's name is Anna" },
        ],
        quiz: [
          { type: "mcq", q: "How do you say 'father' in Italian?", options: ["padre", "madre", "fratello", "figlio"], a: "padre" },
          { type: "fill", q: "My mother: ___ madre", a: "mia" },
          { type: "mcq", q: "Why is 'mio padre' used WITHOUT an article (not 'il mio padre')?", options: ["It's incorrect grammar", "Singular unmodified family members drop the article", "Articles are never used", "Padre is plural"], a: "Singular unmodified family members drop the article" },
          { type: "mcq", q: "Which is the correct form for 'my brothers'?", options: ["miei fratelli", "i miei fratelli", "mio fratelli", "le mie fratelli"], a: "i miei fratelli" },
          { type: "fill", q: "Daughter: ___", a: "figlia" },
          { type: "mcq", q: "'Nonna' means:", options: ["Mother", "Aunt", "Grandmother", "Sister"], a: "Grandmother" },
          { type: "mcq", q: "Someone says 'Questa è la mia famiglia.' They are:", options: ["Saying goodbye", "Introducing their family", "Asking your name", "Ordering food"], a: "Introducing their family" },
          { type: "fill", q: "Friend (male): ___", a: "amico" },
          { type: "mcq", q: "'Moglie' means:", options: ["Husband", "Wife", "Daughter", "Mother-in-law"], a: "Wife" },
        ],
      },
      {
        id: 5,
        title: "Food & Dining",
        grammar: "'Vorrei' (I would like) is the polite way to order. 'Il conto' = the bill. Italians say 'Buon appetito' before meals.",
        vocab: [
          { term: "pane", meaning: "bread" },
          { term: "acqua", meaning: "water" },
          { term: "vino", meaning: "wine" },
          { term: "caffè", meaning: "coffee" },
          { term: "pasta", meaning: "pasta" },
          { term: "pizza", meaning: "pizza" },
          { term: "formaggio", meaning: "cheese" },
          { term: "carne / pesce", meaning: "meat / fish" },
        ],
        phrases: [
          { term: "Il conto, per favore", meaning: "The bill, please" },
          { term: "Buon appetito", meaning: "Enjoy your meal" },
          { term: "Vorrei un caffè", meaning: "I would like a coffee" },
        ],
        quiz: [
          { type: "mcq", q: "At an Italian restaurant, you politely order with:", options: ["Voglio", "Dammi", "Vorrei", "Ho bisogno"], a: "Vorrei" },
          { type: "fill", q: "Water: ___", a: "acqua" },
          { type: "mcq", q: "Before starting a meal, Italians say:", options: ["Arrivederci", "Buon appetito", "Grazie", "Buona notte"], a: "Buon appetito" },
          { type: "mcq", q: "After dinner, you ask the waiter:", options: ["Il conto, per favore", "Buon appetito", "Vorrei", "Ciao"], a: "Il conto, per favore" },
          { type: "fill", q: "Bread: ___", a: "pane" },
          { type: "mcq", q: "Which is a vegetarian-friendly option?", options: ["carne", "pesce", "formaggio", "pollo"], a: "formaggio" },
          { type: "fill", q: "Coffee: ___", a: "caffè" },
          { type: "mcq", q: "'Vorrei un bicchiere di vino' means:", options: ["I want a bottle of wine", "I would like a glass of wine", "I have wine", "Wine is good"], a: "I would like a glass of wine" },
          { type: "mcq", q: "Which dish is most iconic to Italian cuisine?", options: ["pane", "pasta", "acqua", "formaggio"], a: "pasta" },
        ],
      },
      {
        id: 6,
        title: "Travel & Directions",
        grammar: "Use 'Dov'è…?' to ask 'Where is…?' Directions: a destra (right), a sinistra (left), sempre dritto (straight ahead).",
        vocab: [
          { term: "stazione", meaning: "station" },
          { term: "aeroporto", meaning: "airport" },
          { term: "albergo / hotel", meaning: "hotel" },
          { term: "bagno", meaning: "bathroom" },
          { term: "strada / via", meaning: "street / road" },
          { term: "destra / sinistra", meaning: "right / left" },
          { term: "vicino / lontano", meaning: "near / far" },
        ],
        phrases: [
          { term: "Dov'è il bagno?", meaning: "Where is the bathroom?" },
          { term: "Sempre dritto", meaning: "Straight ahead" },
          { term: "A destra", meaning: "To the right" },
        ],
        quiz: [
          { type: "mcq", q: "You're at a café in Florence and need the bathroom. You ask:", options: ["Quanto costa?", "Dov'è il bagno?", "Che ora è?", "Come ti chiami?"], a: "Dov'è il bagno?" },
          { type: "fill", q: "Right: a ___", a: "destra" },
          { type: "mcq", q: "A local says 'Sempre dritto.' You should go:", options: ["Right", "Left", "Straight ahead", "Backward"], a: "Straight ahead" },
          { type: "mcq", q: "You're traveling by train. You go to the:", options: ["aeroporto", "stazione", "albergo", "bagno"], a: "stazione" },
          { type: "fill", q: "Airport: ___", a: "aeroporto" },
          { type: "mcq", q: "'Vicino' is the opposite of:", options: ["destra", "lontano", "sinistra", "strada"], a: "lontano" },
          { type: "mcq", q: "Which question correctly asks 'Where is the hotel?'", options: ["Dov'è l'albergo?", "Quanto albergo?", "Albergo dove?", "Che albergo?"], a: "Dov'è l'albergo?" },
          { type: "fill", q: "Left: ___", a: "sinistra" },
          { type: "mcq", q: "If a place is 'lontano', it is:", options: ["near", "expensive", "far", "closed"], a: "far" },
        ],
      },
    ],
  },
};

function defaultLessonMeta(lesson, courseName) {
  if (!lesson.intro) {
    lesson.intro = `In this lesson on ${courseName}, you will study "${lesson.title}" through vocabulary, phrases, and grammar—then prove your knowledge in a quiz.`;
  }
  if (!lesson.objectives) {
    lesson.objectives = [
      `Learn key words for ${lesson.title}`,
      "Practice useful phrases",
      "Apply the grammar tip",
      "Pass the lesson quiz with 70% or higher",
    ];
  }
}

Object.keys(COURSES).forEach((lang) => {
  const course = COURSES[lang];
  const intro = COURSE_INTROS[lang];
  if (intro) {
    defaultLessonMeta(intro, course.name);
    course.lessons = [intro, ...course.lessons.filter((l) => l.id !== 0)];
  }
  course.lessons.forEach((lesson) => defaultLessonMeta(lesson, course.name));
});
