const COURSES = {
  spanish: {
    name: "Spanish",
    flag: "🇪🇸",
    native: "Español",
    lessons: [
      {
        id: 1,
        title: "Greetings & Introductions",
        grammar: "Spanish greetings vary by time of day. Use tú (informal) with friends and usted (formal) with strangers or elders.",
        vocab: [
          { term: "Hola", meaning: "Hello" },
          { term: "Buenos días", meaning: "Good morning" },
          { term: "Buenas tardes", meaning: "Good afternoon" },
          { term: "Buenas noches", meaning: "Good evening / night" },
          { term: "Adiós", meaning: "Goodbye" },
          { term: "Por favor", meaning: "Please" },
          { term: "Gracias", meaning: "Thank you" },
        ],
        phrases: [
          { term: "¿Cómo te llamas?", meaning: "What is your name? (informal)" },
          { term: "Me llamo…", meaning: "My name is…" },
          { term: "Mucho gusto", meaning: "Nice to meet you" },
        ],
        quiz: [
          { type: "mcq", q: "How do you say 'Hello'?", options: ["Hola", "Adiós", "Gracias", "Por favor"], a: "Hola" },
          { type: "mcq", q: "What does 'Buenos días' mean?", options: ["Good night", "Good morning", "Goodbye", "Thank you"], a: "Good morning" },
          { type: "fill", q: "Thank you: ___", a: "gracias" },
          { type: "mcq", q: "'Mucho gusto' means:", options: ["See you later", "Nice to meet you", "Excuse me", "How are you?"], a: "Nice to meet you" },
          { type: "fill", q: "Goodbye: ___", a: "adiós" },
        ],
      },
      {
        id: 2,
        title: "Numbers & Basics",
        grammar: "Numbers 1–15 are essential for shopping and schedules. Uno changes to un before masculine nouns (un libro).",
        vocab: [
          { term: "uno", meaning: "one" },
          { term: "dos", meaning: "two" },
          { term: "tres", meaning: "three" },
          { term: "cuatro", meaning: "four" },
          { term: "cinco", meaning: "five" },
          { term: "diez", meaning: "ten" },
          { term: "quince", meaning: "fifteen" },
        ],
        phrases: [
          { term: "¿Cuánto cuesta?", meaning: "How much does it cost?" },
          { term: "Son cinco euros", meaning: "It's five euros" },
        ],
        quiz: [
          { type: "mcq", q: "What is 'tres'?", options: ["two", "three", "four", "ten"], a: "three" },
          { type: "fill", q: "Five in Spanish: ___", a: "cinco" },
          { type: "mcq", q: "'¿Cuánto cuesta?' means:", options: ["Where is it?", "How much?", "What time?", "How many?"], a: "How much?" },
          { type: "fill", q: "Ten: ___", a: "diez" },
          { type: "mcq", q: "Which is 'four'?", options: ["dos", "tres", "cuatro", "cinco"], a: "cuatro" },
        ],
      },
      {
        id: 3,
        title: "Everyday Verbs",
        grammar: "Regular -ar verbs: remove -ar and add -o, -as, -a… Example: hablar → hablo (I speak).",
        vocab: [
          { term: "hablar", meaning: "to speak" },
          { term: "estudiar", meaning: "to study" },
          { term: "trabajar", meaning: "to work" },
          { term: "comer", meaning: "to eat" },
          { term: "vivir", meaning: "to live" },
        ],
        phrases: [
          { term: "Yo hablo español", meaning: "I speak Spanish" },
          { term: "Ella estudia mucho", meaning: "She studies a lot" },
        ],
        quiz: [
          { type: "mcq", q: "'hablar' means:", options: ["to eat", "to speak", "to live", "to work"], a: "to speak" },
          { type: "fill", q: "to eat: ___", a: "comer" },
          { type: "mcq", q: "'Yo hablo español' means:", options: ["I eat Spanish", "I speak Spanish", "I study Spanish", "I live in Spain"], a: "I speak Spanish" },
          { type: "fill", q: "to live: ___", a: "vivir" },
          { type: "mcq", q: "'trabajar' means:", options: ["to work", "to walk", "to wait", "to travel"], a: "to work" },
        ],
      },
    ],
  },
  french: {
    name: "French",
    flag: "🇫🇷",
    native: "Français",
    lessons: [
      {
        id: 1,
        title: "Greetings & Politeness",
        grammar: "French uses formal (vous) and informal (tu) address. Always say Bonjour when entering a shop.",
        vocab: [
          { term: "Bonjour", meaning: "Hello / Good day" },
          { term: "Bonsoir", meaning: "Good evening" },
          { term: "Salut", meaning: "Hi (informal)" },
          { term: "Au revoir", meaning: "Goodbye" },
          { term: "Merci", meaning: "Thank you" },
          { term: "S'il vous plaît", meaning: "Please (formal)" },
        ],
        phrases: [
          { term: "Comment allez-vous?", meaning: "How are you? (formal)" },
          { term: "Je m'appelle…", meaning: "My name is…" },
          { term: "Enchanté(e)", meaning: "Pleased to meet you" },
        ],
        quiz: [
          { type: "mcq", q: "'Bonjour' is used for:", options: ["Good night only", "Hello / Good day", "Goodbye", "Thank you"], a: "Hello / Good day" },
          { type: "fill", q: "Thank you: ___", a: "merci" },
          { type: "mcq", q: "'Enchanté' means:", options: ["Good luck", "Pleased to meet you", "Excuse me", "See you soon"], a: "Pleased to meet you" },
          { type: "fill", q: "Goodbye: ___ revoir", a: "au" },
          { type: "mcq", q: "Informal 'hi' is:", options: ["Bonsoir", "Salut", "Merci", "Bonjour"], a: "Salut" },
        ],
      },
      {
        id: 2,
        title: "Numbers & Shopping",
        grammar: "French numbers 1–10: un, deux, trois… Sixty is soixante; seventy is soixante-dix.",
        vocab: [
          { term: "un / une", meaning: "one" },
          { term: "deux", meaning: "two" },
          { term: "trois", meaning: "three" },
          { term: "cinq", meaning: "five" },
          { term: "dix", meaning: "ten" },
        ],
        phrases: [
          { term: "C'est combien?", meaning: "How much is it?" },
          { term: "Je voudrais…", meaning: "I would like…" },
        ],
        quiz: [
          { type: "mcq", q: "'trois' is:", options: ["two", "three", "ten", "five"], a: "three" },
          { type: "fill", q: "Ten: ___", a: "dix" },
          { type: "mcq", q: "'C'est combien?' means:", options: ["What time?", "How much?", "Where?", "Who?"], a: "How much?" },
          { type: "fill", q: "Five: ___", a: "cinq" },
          { type: "mcq", q: "'Je voudrais' means:", options: ["I have", "I would like", "I can", "I am"], a: "I would like" },
        ],
      },
      {
        id: 3,
        title: "Common Verbs",
        grammar: "être (to be) and avoir (to have) are irregular. Je suis = I am; J'ai = I have.",
        vocab: [
          { term: "être", meaning: "to be" },
          { term: "avoir", meaning: "to have" },
          { term: "aller", meaning: "to go" },
          { term: "faire", meaning: "to do / make" },
          { term: "parler", meaning: "to speak" },
        ],
        phrases: [
          { term: "Je suis étudiant", meaning: "I am a student" },
          { term: "J'ai faim", meaning: "I am hungry (lit. I have hunger)" },
        ],
        quiz: [
          { type: "mcq", q: "'être' means:", options: ["to have", "to be", "to go", "to speak"], a: "to be" },
          { type: "fill", q: "to have: ___", a: "avoir" },
          { type: "mcq", q: "'J'ai faim' means:", options: ["I am tired", "I am hungry", "I am happy", "I am late"], a: "I am hungry" },
          { type: "fill", q: "to go: ___", a: "aller" },
          { type: "mcq", q: "'Je suis étudiant' means:", options: ["I have a student", "I am a student", "I see a student", "I want to study"], a: "I am a student" },
        ],
      },
    ],
  },
  german: {
    name: "German",
    flag: "🇩🇪",
    native: "Deutsch",
    lessons: [
      {
        id: 1,
        title: "Greetings & Basics",
        grammar: "German capitalizes all nouns. Guten Tag is neutral-formal; Hallo is casual.",
        vocab: [
          { term: "Hallo", meaning: "Hello" },
          { term: "Guten Morgen", meaning: "Good morning" },
          { term: "Guten Tag", meaning: "Good day" },
          { term: "Gute Nacht", meaning: "Good night" },
          { term: "Danke", meaning: "Thank you" },
          { term: "Bitte", meaning: "Please / You're welcome" },
        ],
        phrases: [
          { term: "Wie heißen Sie?", meaning: "What is your name? (formal)" },
          { term: "Ich heiße…", meaning: "My name is…" },
          { term: "Freut mich", meaning: "Nice to meet you" },
        ],
        quiz: [
          { type: "mcq", q: "'Guten Morgen' means:", options: ["Good night", "Good morning", "Goodbye", "Hello"], a: "Good morning" },
          { type: "fill", q: "Thank you: ___", a: "danke" },
          { type: "mcq", q: "'Bitte' can mean:", options: ["Only goodbye", "Please / You're welcome", "Good night", "Excuse me only"], a: "Please / You're welcome" },
          { type: "fill", q: "My name is: Ich ___", a: "heiße" },
          { type: "mcq", q: "'Freut mich' means:", options: ["I'm sorry", "Nice to meet you", "See you", "Good luck"], a: "Nice to meet you" },
        ],
      },
      {
        id: 2,
        title: "Numbers & Time",
        grammar: "German numbers: eins, zwei, drei… Uhr means o'clock (Es ist drei Uhr).",
        vocab: [
          { term: "eins", meaning: "one" },
          { term: "zwei", meaning: "two" },
          { term: "drei", meaning: "three" },
          { term: "fünf", meaning: "five" },
          { term: "zehn", meaning: "ten" },
        ],
        phrases: [
          { term: "Wie viel kostet das?", meaning: "How much does that cost?" },
          { term: "Wie spät ist es?", meaning: "What time is it?" },
        ],
        quiz: [
          { type: "mcq", q: "'drei' is:", options: ["two", "three", "five", "ten"], a: "three" },
          { type: "fill", q: "Ten: ___", a: "zehn" },
          { type: "mcq", q: "'Wie spät ist es?' asks:", options: ["Where?", "What time?", "Why?", "Who?"], a: "What time?" },
          { type: "fill", q: "Five: ___", a: "fünf" },
          { type: "mcq", q: "'zwei' means:", options: ["one", "two", "three", "ten"], a: "two" },
        ],
      },
    ],
  },
  japanese: {
    name: "Japanese",
    flag: "🇯🇵",
    native: "日本語",
    lessons: [
      {
        id: 1,
        title: "Greetings & Courtesy",
        grammar: "Japanese has polite (です/ます) and casual forms. Bowing accompanies greetings. は is pronounced 'wa' as a particle.",
        vocab: [
          { term: "こんにちは", meaning: "Hello (afternoon)" },
          { term: "おはよう", meaning: "Good morning" },
          { term: "こんばんは", meaning: "Good evening" },
          { term: "さようなら", meaning: "Goodbye" },
          { term: "ありがとう", meaning: "Thank you" },
          { term: "すみません", meaning: "Excuse me / Sorry" },
        ],
        phrases: [
          { term: "はじめまして", meaning: "Nice to meet you" },
          { term: "お元気ですか", meaning: "How are you? (polite)" },
          { term: "よろしくお願いします", meaning: "Please treat me well (common intro)" },
        ],
        quiz: [
          { type: "mcq", q: "'ありがとう' means:", options: ["Goodbye", "Thank you", "Hello", "Excuse me"], a: "Thank you" },
          { type: "mcq", q: "'はじめまして' is used when:", options: ["Leaving", "Meeting someone new", "Eating", "Sleeping"], a: "Meeting someone new" },
          { type: "mcq", q: "'こんばんは' means:", options: ["Good morning", "Good evening", "Good night only", "Hello (morning)"], a: "Good evening" },
          { type: "mcq", q: "'すみません' can mean:", options: ["Thank you", "Excuse me / Sorry", "Goodbye", "Good luck"], a: "Excuse me / Sorry" },
          { type: "mcq", q: "Polite 'thank you very much' is often:", options: ["さようなら", "ありがとうございます", "おはよう", "こんにちは"], a: "ありがとうございます" },
        ],
      },
      {
        id: 2,
        title: "Numbers & Counters",
        grammar: "Japanese uses counters after numbers (一つ hitotsu = one thing). Native numbers 1–5: 一, 二, 三, 四, 五.",
        vocab: [
          { term: "一 (いち)", meaning: "one" },
          { term: "二 (に)", meaning: "two" },
          { term: "三 (さん)", meaning: "three" },
          { term: "四 (よん/し)", meaning: "four" },
          { term: "五 (ご)", meaning: "five" },
          { term: "十 (じゅう)", meaning: "ten" },
        ],
        phrases: [
          { term: "いくらですか", meaning: "How much is it?" },
          { term: "〜をください", meaning: "Please give me…" },
        ],
        quiz: [
          { type: "mcq", q: "'三' (さん) is:", options: ["two", "three", "five", "ten"], a: "three" },
          { type: "mcq", q: "'いくらですか' means:", options: ["Where?", "How much?", "What?", "When?"], a: "How much?" },
          { type: "mcq", q: "'五' is:", options: ["four", "five", "six", "ten"], a: "five" },
          { type: "mcq", q: "'十' (じゅう) is:", options: ["five", "seven", "ten", "one"], a: "ten" },
          { type: "mcq", q: "'二' is:", options: ["one", "two", "three", "four"], a: "two" },
        ],
      },
    ],
  },
  italian: {
    name: "Italian",
    flag: "🇮🇹",
    native: "Italiano",
    lessons: [
      {
        id: 1,
        title: "Greetings & Introductions",
        grammar: "Italian vowels are clear and open. Lei is formal 'you'; tu is informal.",
        vocab: [
          { term: "Ciao", meaning: "Hi / Bye (informal)" },
          { term: "Buongiorno", meaning: "Good morning / day" },
          { term: "Buonasera", meaning: "Good evening" },
          { term: "Arrivederci", meaning: "Goodbye" },
          { term: "Grazie", meaning: "Thank you" },
          { term: "Prego", meaning: "You're welcome / Please" },
        ],
        phrases: [
          { term: "Come ti chiami?", meaning: "What is your name?" },
          { term: "Mi chiamo…", meaning: "My name is…" },
          { term: "Piacere", meaning: "Pleased to meet you" },
        ],
        quiz: [
          { type: "mcq", q: "'Buongiorno' means:", options: ["Good night", "Good morning/day", "Goodbye", "Thanks"], a: "Good morning/day" },
          { type: "fill", q: "Thank you: ___", a: "grazie" },
          { type: "mcq", q: "'Piacere' means:", options: ["Please", "Pleased to meet you", "Excuse me", "Good luck"], a: "Pleased to meet you" },
          { type: "fill", q: "Goodbye (formal): ___", a: "arrivederci" },
          { type: "mcq", q: "'Prego' often means:", options: ["Goodbye", "You're welcome", "Good night", "Hello"], a: "You're welcome" },
        ],
      },
      {
        id: 2,
        title: "Essential Verbs",
        grammar: "Verbs end in -are, -ere, -ire. Parlare (to speak): parlo, parli, parla…",
        vocab: [
          { term: "essere", meaning: "to be" },
          { term: "avere", meaning: "to have" },
          { term: "parlare", meaning: "to speak" },
          { term: "mangiare", meaning: "to eat" },
          { term: "andare", meaning: "to go" },
        ],
        phrases: [
          { term: "Sono di Roma", meaning: "I'm from Rome" },
          { term: "Ho fame", meaning: "I'm hungry" },
        ],
        quiz: [
          { type: "mcq", q: "'essere' means:", options: ["to have", "to be", "to go", "to eat"], a: "to be" },
          { type: "fill", q: "to eat: ___", a: "mangiare" },
          { type: "mcq", q: "'Ho fame' means:", options: ["I am tired", "I am hungry", "I am happy", "I am here"], a: "I am hungry" },
          { type: "fill", q: "to speak: ___", a: "parlare" },
          { type: "mcq", q: "'andare' means:", options: ["to go", "to stay", "to speak", "to have"], a: "to go" },
        ],
      },
    ],
  },
};
